### ISSUE TITLE
YOUR PROGRAM SUCKS

### ISSUE THREAD

**Issue by SapphireBulletBill** [jakcron/nstool#109]
IT DOESN'T EVEN OPEN.
FIX IT.

**Comment by jakcron** [comment]
Hi @JoeChungusThrows thanks for reaching out. 

NSTool is currently in the conceptual phase. You have to imagine it working until I figure out how to read Nintendo Switch files. 

I hope one day it will open 😁 I will tag you in this comment once it does.

**Comment by VolkerSchlegel** [comment]
It is a command line program, of course it doesn't open any window 🤦‍♂️
