### ISSUE TITLE
Extract only certain files from NSP (to get .cnmt)?

### ISSUE THREAD

**Issue by station7** [jakcron/nstool#62]
Many thanks for this great tool. Is it possible to extract only certain files from a .nsp file instead of extracting the entire nsp? Or is there any other way or shortcut to get directly to the .cnmt file without extracting the entire nsp and extracting part0 from cnmt.nca?

**Comment by jakcron** [comment]
Presently it is not possible to extract specific files from an NSP or access the CMNT directly. 

I plan to make reading NSPs less annoying in the future but I haven’t decided the best way to do it.

**Comment by station7** [comment]
Hi Jack, 

thanks for your answer. Getting faster to the CMNT would be perfect for me - I am looking forward to the progress of nstool. Thanks!
