### ISSUE TITLE
How to extract NCA patch file?

### ISSUE THREAD

**Issue by Kimi-Arthur** [jakcron/nstool#64]
The tool is very useful that I can extract all `.nsp` files I got. But I only succeeded in extracting `.nca` files for base game.

For all patch/update, I got the following error:

```
[NCA Header]
  Format Type:     NCA3
  Dist. Type:      Download
  Content Type:    Program
  Key Generation:  0
  Kaek Index:      Application (0)
  Size:            0x926a400
  ProgID:          0x01001d900d9ac000
  Content Index:   0
  SdkAddon Ver.:   v134348800 (8.2.0)
[PartitionFS]
  Type:        PFS0
  FileNum:     4
  MountPoint:  program:/code/
[WARNING] NCA Partition 1 not readable. (EncryptionType(AesCtrEx): UNSUPPORTED)
```

One example would be [this file](https://drive.google.com/file/d/1jH7_-uVOatr2iRuyTEX_keteOo44YxJM/view),  where the extracted file with name `8759c093c9ac45ba455929e61d4a0195.nca` cannot be further extracted and will produce the error above.

**Comment by jakcron** [comment]
I'm sorry but NSTool does not support patch/update NCA files yet.

It's planned for the future though.

**Comment by mpql** [comment]
No rush whatsoever; I just wanted to ping this issue and see if it's still planned. Thanks!

**Comment by jakcron** [comment]
@mpql @Kimi-Arthur through the magic of someone doing the hard work for me, this will be put into an official release soon :)

**Comment by jakcron** [comment]
@Kimi-Arthur @mpql Thank you for your patience.

Thanks to @sagumamugas this is now supported by NSTool v1.7.0 (https://github.com/jakcron/nstool/releases/tag/v1.7.0-r2)

If you wish to extract a NCA Patch file, you need to specify the base NCA file using the CLI base NCA argument `--basenca`. If you have any questions feel free to ask here.

**Comment by ghost** [comment]
[WARNING] NCA Partition 1 not readable. (Indirect storage not ascending ordered.)
anyone can help me fixing this!

**Comment by jakcron** [comment]
@Adityabyahut please open a new issue with some more details:
* the name of the game you are extracting 
* The exact nstool command that you ran
* The full output of nstool from running that command

thanks :)

**Comment by basilicon** [comment]
I am getting a similar issue.  I am trying to extract the SMM2 3.0.2 update, and it is giving me two warnings:
```
nstool.exe -k .\prod.keys --basenca "./SMM2/ca09dd281fba9954014068c4adc3df2b.nca" -x ./output/9014125f54075fd01aa2bce70130028a/ ./output/9014125f54075fd01aa2bce70130028a.nca
[NCA Header]
  Format Type:     NCA3
  Dist. Type:      Download
  Content Type:    Program
  Key Generation:  8
  Sig. Generation: 0
  Kaek Index:      Application (0)
  Size:            0xe9b1a00
  ProgID:          0x01009b90006dc000
  Content Index:   0
  SdkAddon Ver.:   7.4.0 (v117702656)
  RightsId:        01009B90006DC8000000000000000008
[WARNING] NCA Partition 0 not readable. (AES-CTR Key was not determined)
[WARNING] NCA Partition 1 not readable. (AES-CTR Key was not determined)
[ContentArchive/Extract]
```
I was able to extract some of the other NCA files, but not this one or a different one.  I looked at the metadata and found that it is actually the Program.nca and the HtmlDocument.nca files.
