### ISSUE TITLE
Where are the extracted game files of XCI image

### ISSUE THREAD

**Issue by frank1995f** [jakcron/nstool#77]
I used nstool -x ./extract_dir/ C:\Users\frank\Downloads\Digimon_Story_Cyber_Sleuth_Hackers_Memory_JPN_V1.0.2_Switch-xci.com.xci
It extracted successfully, but I don't know where the extracted game files are....

**Comment by jakcron** [comment]
Where is nstool on your computer? It looks like “extract_dir” would be extracted to the same place nstool is.

**Comment by frank1995f** [comment]
Thank you I already did it with yuzu emulator.... but I discovered it works only if you put the nstool in the System32 folder I guess the extract dir would appear there as a folder? I guess?

**Comment by jakcron** [comment]
If you put nstool in system32 then “extract_dir” will be in whatever directory you navigated to with command prompt when you extracted the game rom. Which is usually your user directory.
