### ISSUE TITLE
cant extract minecraft romfs

### ISSUE THREAD

**Issue by KuromeSan** [jakcron/nstool#78]
nstool.exe -x ./ romfs.bin
[RomFs]
  DirNum:      88
  FileNum:     1284
[RomFs/Extract]
Saving ./Empty.txt...
[tc::io::SubStream::seek() ERROR] Failed to set stream position (stream is disposed)

**Comment by jakcron** [comment]
Hello thank you for opening this issue. Can you please answer some questions:

1) What version of NSTool are you using?

2) What OS are you using to run NSTool

3) What is the titleID and version of this Minecraft title you're trying to extract the RomFS from?

**Comment by KuromeSan** [comment]
What version of NSTool are you using? 1.6.2
What operating system are you using? Windows 11
What is the titleID and version of this Minecraft title you're trying to extract the RomFS from? 0100D71004694000

its BASE GAME ..

**Comment by jakcron** [comment]
Thank you, i'll try to locate a copy and test myself.

This looks like a NSTool bug, so I'll respond here when I figure out the issue and have a fix.

**Comment by jakcron** [comment]
Oh wow this was a very dumb bug indeed. Easy fix.

**Comment by jakcron** [comment]
Please try this build of NSTool:
[nstool-win_x64.zip](https://github.com/jakcron/nstool/suites/5904604375/artifacts/201130700)

**Comment by KuromeSan** [comment]
fixed.
