### ISSUE TITLE
Verification and Extraction failing on DBI NROs

### ISSUE THREAD

**Issue by rlaphoenix** [jakcron/nstool#86]
Through nton, it's failing both verification and nacp extraction calls in the same way. I've tried various versions of DBI NROs, like the last few releases, releases from v3xx era, v2xx era, and so on with the same issue.

The only actual error message I seem to get is `[tc::io::FileStream::read() ERROR] ptr was null`

![image](https://user-images.githubusercontent.com/17136956/202843001-9b8d3c19-b3c2-4afc-854e-3be7548b957a.png)

**Comment by jakcron** [comment]
Thank you for filing this issue. After some investigation, the issue appears to be due to NSTool not properly handling the empty RomFs binaries.

I'll respond here when I fix the issue, seems relatively simple.

**Comment by jakcron** [comment]
@rlaphoenix please try [NSTool v1.6.6](https://github.com/jakcron/nstool/releases/tag/v1.6.6) and let me know if that fixes the bug for you.

**Comment by rlaphoenix** [comment]
It does seem to fix it, nice one 👍
