### ISSUE TITLE
Problem NCA 

### ISSUE THREAD

**Issue by AinzOoalGown-fun** [jakcron/nstool#90]
Hello
I used XCI-Explorer-v2.0.0 extracted .nca and .tik form .Nsp file.

I don't know the command to extract  with nstool.exe.

after I extracted .nca with the following command but there is an error

![Capture d’écran 2023-01-28 225637](https://user-images.githubusercontent.com/73220716/215292922-3dd6f482-10d0-421e-b322-a27c8a488db2.png)

Thank you for you help -_-

**Comment by jakcron** [comment]
That is a bit confounding. From looking at the errors, it is either the ticket was somehow invalid (NSTool is generating the wrong content key). Or the NCA is corrupted.

I'm not sure the best way to solve this, but you can try adding these extra command flags after `-k "prod.keys"`: `-y -v`

This will enable full verification of the file, and enable verbose output. Hopefully the combination of the two will hint to why NSTool is failing for this file.

**Comment by AinzOoalGown-fun** [comment]
> That is a bit confounding. From looking at the errors, it is either the ticket was somehow invalid (NSTool is generating the wrong content key). Or the NCA is corrupted.
> 
> I'm not sure the best way to solve this, but you can try adding these extra command flags after `-k "prod.keys"`: `-y -v`
> 
> This will enable full verification of the file, and enable verbose output. Hopefully the combination of the two will hint to why NSTool is failing for this file.
 dont work
[error.txt](https://github.com/jakcron/nstool/files/10528742/error.txt)

**Comment by AinzOoalGown-fun** [comment]
What is command to extract  Nsp with nstool.exe ? 
Thank you-_-

**Comment by jakcron** [comment]
`nstool -x nspextracted your.nsp`

**Comment by AinzOoalGown-fun** [comment]
sorry for the wait, I had to try several commands.

> `nstool -x nspextracted your.nsp`

[same error + new.txt](https://github.com/jakcron/nstool/files/10528808/same.error.%2B.new.txt)
![Capture d’écran 2023-01-29 033013](https://user-images.githubusercontent.com/73220716/215301148-159b7f03-2e70-4aef-b313-576b096e7aa3.png)

**Comment by jakcron** [comment]
I'll give you some specific steps now I can see what the file names are:

1) Extract NSP
`nstool.exe -k "prod.keys" -x "nspextracted" "file.nsp"`

2) Check the ticket file (so I can see the titlekey and other data)
`nstool.exe -k "prod.keys" -v "nspextracted\0100ea6014bb8000000000000000000b.tik"`

With the output of this I may be able to figure out what's happening.

**Comment by AinzOoalGown-fun** [comment]
> I'll give you some specific steps now I can see what the file names are:
> 
> 1. Extract NSP
>    `nstool.exe -k "prod.keys" -x "nspextracted" "file.nsp"`
> 2. Check the ticket file (so I can see the titlekey and other data)
>    `nstool.exe -k "prod.keys" -v "nspextracted\0100ea6014bb8000000000000000000b.tik"`
> 
> With the output of this I may be able to figure out what's happening.

nstool.exe -k "prod.keys" -x "nspextracted" "file.nsp"   is work.

[output.txt](https://github.com/jakcron/nstool/files/10528845/output.txt)

**Comment by jakcron** [comment]
I can't see anything wrong with the ticket or how it's being decrypted. So maybe the NCA was extracted wrong using the original tool. 

We can try two ways to decrypt/extract the NCA:
1) Try to extract NCA (and supply raw titlekey from ticket)
`nstool.exe -k "prod.keys" --titlekey F354A70FA85EE2E5922AD04FEAD828C5 -v -x "narutoprogram" "nspextracted\d5bdc4b294e5fdb8b4845510c0512a2f.nca"`
2) Try to extract NCA (and supply raw decrypted titlekey from ticket)
`nstool.exe -k "prod.keys" --contentkey AE83CAC1F2A47088CC2A4636CBC0CE61 -v -x "narutoprogram" "nspextracted\d5bdc4b294e5fdb8b4845510c0512a2f.nca"`

**Comment by AinzOoalGown-fun** [comment]
same error 
[outpupv2.txt](https://github.com/jakcron/nstool/files/10528874/outpupv2.txt)

**Comment by jakcron** [comment]
Unfortunately I can't figure this one out. Your file NSP file might be corrupted.

**Comment by AinzOoalGown-fun** [comment]
> Unfortunately I can't figure this one out. Your file NSP file might be corrupted.
no it works, I tested it .
maybe you have to extract with romfs

**Comment by AinzOoalGown-fun** [comment]
I tried another program and it works with titlekey F354A70FA85EE2E5922AD04FEAD828C5
https://github.com/bodyXY/Ultimate-Material-Hactool-GUI
it's your program that's the problem. 
Thank you for you help

**Comment by jakcron** [comment]
Thank you for your feedback

**Comment by jakcron** [comment]
What is the name of this game by the way?

**Comment by AinzOoalGown-fun** [comment]
just dance

**Comment by AinzOoalGown-fun** [comment]
close issue -_-

**Comment by jakcron** [comment]
For future investigation if I get time~

ContentType: Download Version (eShop)
ContentVersion: BaseGame
Title: Just Dance 2022
ProgramId: `0100EA6014BB800`
KeyGeneration: 11 (`master_key_0a`)
RightsId: `0100EA6014BB8000000000000000000B`
TitleKey: `F354A70FA85EE2E5922AD04FEAD828C5`

**Comment by AinzOoalGown-fun** [comment]
ok -_-
