### ISSUE TITLE
NCA patch failed with some errors (Indirect storage not ascending ordered.)

### ISSUE THREAD

**Issue by ghost** [jakcron/nstool#98]
game - Pokémon Violet
nstool --basenca ./b.nca -x ./out u.nca

Error:

[WARNING] NCA Header Main Signature: FAIL
[WARNING] ACID Signature: FAIL (Failed to verify Access Control Info Desc)
[NCA Header]
  Format Type:     NCA3
  Dist. Type:      Download
  Content Type:    Program
  Key Generation:  10
  Sig. Generation: 0
  Kaek Index:      Application (0)
  Size:            0xb78af000
  ProgID:          0x0100abf008968000
  Content Index:   0
  SdkAddon Ver.:   7.7.0 (v117899264)
[WARNING] NCA Partition 1 not readable. (Indirect storage not ascending ordered.)
[ContentArchive/Extract]
Saving ./out/0/main...
Saving ./out/0/main.npdm...
Saving ./out/0/rtld...
Saving ./out/0/sdk...
Saving ./out/0/subsdk0...
Saving ./out/0/subsdk1...

**Comment by jakcron** [comment]
Fixed in https://github.com/jakcron/nstool/releases/tag/v1.9.1
